name: Commitlint Check

on:
  push:
    branches:
      - main

jobs:
  commitlint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Commitlint
        run: npm install --save-dev @commitlint/cli

      - name: Run Commitlint
        run: |
          git log -1 --pretty=format:%s ${{ github.event.before }}..${{ github.event.after }} | npx commitlint
