name: fake branch action

on:
  push:
    branches-ignore:
      - main

jobs:
  fake-job:
    runs-on: ubuntu-latest

    steps:
      - name: echo branch
        env:
          NODE_ENV: development
        run: echo "Now deploying branch:${{ github.ref }} to the test server"

      - name: Print Docker image name
        env:
          DOCKER_IMAGE: my-image
        run: |
          echo "Docker image name: $DOCKER_IMAGE"
