name: fake branch action

on:
  push:
    branches-ignore:
      - main

jobs:
  fake-job:
    runs-on: ubuntu-latest

    steps:
      - name: echo branch
        env:
          NODE_ENV: development
        run: echo "Now deploying branch:${{ github.ref }} to the test server"
