name: Deployment Workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set NODE_ENV to development
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "NODE_ENV=development" >> $GITHUB_ENV

      - name: echo main branch
        run: echo "now deploying to production"
