name: main test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  mocha-supertest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Mocha and supertest
        run: npm run test -- --reporter mocha-junit-reporter --reporter-options mochaFile=test-results.xml

      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test Reports
          path: test-results.xml

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Mocha Tests
          path: test-results.xml
          reporter: java-junit
          fail-on-error: true
